[package]
name = "rusty_hearth"
version = "0.1.0"
authors = ["Aleksander Vognild Burkow <aleksanderburkow@gmail.com>"]

[dependencies]
regex = "0.2.2"
lazy_static = "0.2.8"
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.8"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"